credits {
  header: [
    "Presented by Lambda Innovation",
    "AcademyCraft 1.12.2"
  ]
  staff: [
    [
      "Project Direction",
      "WeAthFolD"
    ],
    [
      "Game Design",
      "Eing",
      "WeAthFolD"
    ],
    [
      "Programming",
      "Paindar",
      "ColdHikari",
      "KSkun",
      "EAirPeter",
      "WeAthFolD",
      "冥狼",
      "acaly"
    ],
    [
      "Art",
      "Nolife_M",
      "H控"
    ],
    [
      "QA",
      "xiao6",
      "BlueFeather"
    ],
    [
      "Website",
      "LeLe",
      "NAT",
      "yinfb",
      "KSkun",
      "Cafe"
    ],
    [
      "Localization",
      "mkpoli (Japanese)",
      "柳荫理乃 (Japanese)",
      "dtraitor (Russian)"
    ],
    [
      "GitHub Contributors",
      "3TUSK",
      "l89669",
      "MrBenjaminBowman",
      "berry64",
    ]
  ]
}
